### Todos los productos
GET http://localhost:8080/products/

### Producto por ID
GET http://localhost:8080/products/668e75d297c8ec166247046b

### Productos por categoria
GET http://localhost:8080/products?category=Desktop

### Productos por nombre (Completo o parcial)
GET http://localhost:8080/products?name=Mouse

### Agregando nuevo producto
POST http://localhost:8080/products
Content-Type: application/json

{
    "codigo": 35,
    "nombre": "Mouse M170 Wireless Mouse",
    "precio": 500,
    "categoria": "Accesorios"
}

### Actualizar parcialmente
PATCH http://localhost:8080/products/edit/668e75d297c8ec166247046b
Content-Type: application/json
{
  "price":100
}

### Eliminar un producto
DELETE http://localhost:8080/products/delete/66a79493d65e51c6696833c4
Content-Type: application/json

### Ruta desconocida (Error 404)
GET  http://localhost:8080/usuarios